### ISSUE TITLE
Migration Failed

### ISSUE THREAD

**Issue by herhand** [vm0993/vmGL#3]
Migration error at
2021_08_04_083715_add_field_status_to_item_outs.php

**To Reproduce**
1. Clone project
2. Install everything
3. Set env
4. Run migration

**Expected behavior**
All migration done normally

**Screenshots**
![image](https://user-images.githubusercontent.com/53961647/130377504-db78e9c6-e3e4-4a17-b376-18a3f3b9f9f1.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser chrome

**Additional context**
db_acc.item_outs' doesn't exist, fix by add this migration before 2021_08_04_083715_add_field_status_to_item_outs.php

**Comment by vm0993** [comment]
Untuk migration dipastikan belum bs di jalankan, krn repo yg ini blum smua masuk.. dan blum di cek.. repo utamanya ak private, ak up setelah selesai implementasi di salah satu sponsor.
