### ISSUE TITLE
Link is broken?

### ISSUE THREAD

**Issue by dv336699** [vm0993/vmGL#5]
http://vimasolusi.com/page/advance-management

![image](https://user-images.githubusercontent.com/930792/130602731-68122b66-4e11-4093-aa8e-157b904ee511.png)

![image](https://user-images.githubusercontent.com/930792/130602584-04b617fd-6aba-4743-95d3-a76061b38504.png)

**Comment by vm0993** [comment]
site will upload all after finish implementation.. all link will be activate after finish implementation.. maybe on September.
